### ISSUE TITLE
erro ao executar a lib

### ISSUE THREAD

**Issue by silviostanzani** [Residencia-Fiep-Turma-2/Grupo_2-Guilherme-Karen-e-Larissa-#14]
(bio) Spraces-MacBook-Pro:Grupo_2-Guilherme-Karen-e-Larissa- silvio$ cat sc.py 
import pkgGKL.DadosFaltantes

#Gerando uma instanciação:

inst = pkgGKL.DadosFaltantes('Exercicio_2/portalbio_export_27-08-2020-14-39-41.csv')

inst.openFile()

#Método .meandf():

print(inst.meandf())

(bio) Spraces-MacBook-Pro:Grupo_2-Guilherme-Karen-e-Larissa- silvio$ python sc.py
Traceback (most recent call last):
  File "sc.py", line 5, in <module>
    inst = pkgGKL.DadosFaltantes('Exercicio_2/portalbio_export_27-08-2020-14-39-41.csv')
TypeError: 'module' object is not callable
(bio) Spraces-MacBook-Pro:Grupo_2-Guilherme-Karen-e-Larissa- silvio$

**Comment by FerreiraLari** [comment]
No momento de gerar uma instanciação o correto seria:
inst = pkgGKL.DadosFaltantes.dadosf('caminho do arquivo csv')
a instrução na Wiki ficou faltando o .dadosf, o erro já foi consertado.
